/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/microsoft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a Microsoft ID token for FlyAccounts tokens
         * @description Validates the Microsoft ID token for the configured organizational tenant and SPA client id. Personal accounts and unknown directories are rejected and MUST NOT create a user. On success, upserts the user. If the work email matches an active invite (case-insensitive), copies invite roles onto the user, sets entryPath to invite, and consumes the invite. Otherwise a newly created user has entryPath organization. Then, if combined permissions still lack access_administration and the work email matches INITIAL_ADMIN_EMAIL, assigns the seeded admin role. Returns an access JWT plus a refresh token.
         */
        post: operations["exchangeMicrosoftToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token and issue a new access JWT
         * @description Redeems a valid refresh token, revokes it, and returns a new pair. Reuse of a rotated or revoked token revokes the token family and returns 401.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the refresh token (and its family) associated with this session. The client MUST then remove tokens from localStorage.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current person, roles, combined permissions, and landing
         * @description Allowed for any signed-in person. Combined permissions are the union of permissions from all assigned roles, loaded from the database for this request. landing.sensitiveFinancialFields is present only when view_sensitive_financial_fields is in that set. landing.sections includes only sections the combined set allows.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Working-and-connected check
         * @description Same StatusResponse as foundation, but not public. HTTP 200 means the frontend reached the backend (connected successfully), even if database or storage is unavailable. Requires a valid access JWT and at least one assigned role. Unsigned callers receive 401. Signed-in callers with no roles receive 403.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signed-in people and unused invites
         * @description Requires access_administration in the caller's combined permissions. Returns a union of Users and active Invites. Unused invites have personType invite and status invited. Signed-in people have personType user and status pending or active.
         */
        get: operations["listPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Roles with attached permissions
         * @description Requires access_administration. Returns roles as data, including attached existing permissions. Creating permission types is not available on this operation.
         */
        get: operations["listRoles"];
        put?: never;
        /**
         * Create a role
         * @description Requires access_administration. Name is required and MUST be unique. Existing permissions are attached with a later call, not created here.
         */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a signed-in person
         * @description Requires access_administration. Removes a listed User and their role assignments. Refresh tokens for that person are revoked. Does not prevent a later organization-based sign-in by the same account. Refused when the change would leave zero signed-in people whose combined permissions include access_administration. Unused invites are cancelled with DELETE /people/invites/{inviteId}, not this operation.
         */
        delete: operations["removePerson"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign an existing role
         * @description Adds the role without replacing roles the person already has. Duplicate assignment is refused. Requires access_administration.
         */
        post: operations["assignRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{userId}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one assigned role
         * @description Removes one assignment. Remaining roles stay. If none remain, the person has no roles (pending access on their next use). Refused when the change would leave zero signed-in people whose combined permissions include access_administration. Unused invites do not count as administrators.
         */
        delete: operations["revokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite a person by organizational work email
         * @description Requires access_administration. Creates an unused invite with zero or more existing roles. The invited person cannot use the application until they sign in. Duplicate active invite of the same email is refused. Invite of an email that already belongs to a listed User is refused. Sending email is not part of this operation.
         */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel an unused invite
         * @description Requires access_administration. Removes an unused invite from the list. Does not prevent a later organization-based sign-in by that email. Consumed invites cannot be cancelled.
         */
        delete: operations["cancelInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/invites/{inviteId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign an existing role to an unused invite
         * @description Adds the role without replacing roles the invite already has. Duplicate assignment is refused. Requires access_administration.
         */
        post: operations["assignInviteRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/invites/{inviteId}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one role from an unused invite
         * @description Removes one InviteRole. Remaining roles stay. Last-admin does not apply (unused invites cannot administer). Requires access_administration.
         */
        delete: operations["revokeInviteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an unused role
         * @description Requires access_administration. Refused while any User or active Invite is assigned the role. Refused when deleting would leave zero signed-in people whose combined permissions include access_administration.
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /**
         * Change a role name or description
         * @description Requires access_administration. Name MUST remain unique. Authorization still follows attached permissions, not the display name.
         */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach an existing permission to a role
         * @description Adds the permission without replacing permissions the role already has. Duplicate attach is refused. Creating permission types is not available. Requires access_administration. Refused when the change would leave zero signed-in people with access_administration (does not apply to attach of a new grant).
         */
        post: operations["attachPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}/permissions/{permissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Detach a permission from a role
         * @description Remaining permissions stay. Every person assigned the role uses the updated combined set on their next request. Refused when the change would leave zero signed-in people whose combined permissions include access_administration. Requires access_administration.
         */
        delete: operations["detachPermission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Existing permission types
         * @description Requires access_administration. Read-only catalog of permission types that roles may attach, grouped by module. Each row is module-level when action is omitted. Creating, renaming, or deleting permission types is not available.
         */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @enum {string} */
            code: "invalid_token" | "personal_account" | "unknown_tenant" | "unauthorized" | "forbidden" | "pending_access" | "not_found" | "duplicate_assignment" | "last_admin_required" | "duplicate_invite" | "already_present" | "duplicate_role_name" | "role_still_assigned" | "duplicate_permission";
            message: string;
        };
        MicrosoftTokenRequest: {
            /** @description Microsoft ID token from MSAL for the configured tenant. */
            idToken: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        TokenResponse: {
            /** @description Short-lived JWT; store in localStorage; send as Bearer. */
            accessToken: string;
            /** @description Opaque token; store in localStorage; send to /auth/refresh. */
            refreshToken: string;
            /** @enum {string} */
            tokenType: "bearer";
            /** @description Access token lifetime in seconds. */
            expiresIn: number;
            user: components["schemas"]["MeResponse"];
        };
        RoleSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
        };
        Permission: {
            /** Format: uuid */
            id: string;
            /** @description Stable code used in authorization checks. Exact match only. */
            code: string;
            /** @description Display label. */
            name: string;
            /** @description Module this permission belongs to (e.g. settings, finance, hr, pmo). Not a closed enum. Catalog grouping only; not an authorization key. */
            module: string;
            /** @description Omitted or null means a whole-module grant. Later rows may set a more specific action (e.g. create, view). A module-level grant does not imply child codes. */
            action?: string;
            /** @description Optional human-readable explanation shown in the Permissions catalog. */
            description?: string;
        };
        Role: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            permissions: components["schemas"]["Permission"][];
        };
        LandingSection: {
            /** @description Permission code that allowed this section. */
            code: string;
            title: string;
            body: string;
        };
        SensitiveFinancialFields: {
            /** @description Demo cost shown only when permitted. Decimal string; not a posted document. */
            cost: string;
            /** @description Demo margin shown only when permitted. Decimal string; not a posted document. */
            margin: string;
        };
        Landing: {
            /** @enum {string} */
            accessState: "pending" | "authorized";
            /** @description Omitted when view_sensitive_financial_fields is not in the combined set. */
            sensitiveFinancialFields?: components["schemas"]["SensitiveFinancialFields"];
            sections: components["schemas"]["LandingSection"][];
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            upn: string;
            roles: components["schemas"]["RoleSummary"][];
            /** @description Combined permission codes for this request. */
            permissions: string[];
            landing: components["schemas"]["Landing"];
        };
        Person: {
            /**
             * Format: uuid
             * @description User.id when personType is user; Invite.id when invite.
             */
            id: string;
            /** @enum {string} */
            personType: "user" | "invite";
            /** @description User.upn or Invite.email. */
            email: string;
            /** @description Present after sign-in; omitted for unused invites. */
            displayName?: string;
            /** @enum {string} */
            status: "invited" | "pending" | "active";
            /**
             * @description How a signed-in User entered. Omitted for unused invites.
             * @enum {string}
             */
            entryPath?: "invite" | "organization";
            roles: components["schemas"]["RoleSummary"][];
        };
        PeopleResponse: {
            people: components["schemas"]["Person"][];
        };
        RolesResponse: {
            roles: components["schemas"]["Role"][];
        };
        PermissionsResponse: {
            permissions: components["schemas"]["Permission"][];
        };
        AssignRoleRequest: {
            /** Format: uuid */
            roleId: string;
        };
        CreateInviteRequest: {
            /** @description Organizational work email. Matching on sign-in is case-insensitive. */
            email: string;
            /**
             * @description Existing roles to pre-assign. Empty means invite with no roles.
             * @default []
             */
            roleIds: string[];
        };
        CreateRoleRequest: {
            name: string;
            description?: string;
        };
        UpdateRoleRequest: {
            name?: string;
            description?: string;
        };
        AttachPermissionRequest: {
            /** Format: uuid */
            permissionId: string;
        };
        StatusResponse: {
            /**
             * @description Backend process handled GET /v1/status.
             * @enum {string}
             */
            service: "ok";
            /**
             * @description Result of a PostgreSQL reachability check (SELECT 1).
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * @description Result of an S3-compatible reachability check (HeadBucket).
             * @enum {string}
             */
            storage: "ok" | "unavailable";
        };
    };
    responses: never;
    parameters: {
        UserId: string;
        RoleId: string;
        InviteId: string;
        PermissionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeMicrosoftToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MicrosoftTokenRequest"];
            };
        };
        responses: {
            /** @description Signed in. Store accessToken and refreshToken in localStorage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid, expired, personal, or wrong-tenant Microsoft token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description New access and refresh tokens. Replace both in localStorage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unknown, expired, revoked, or reused refresh token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "invalid_token",
                     *       "message": "Refresh token is not valid."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access JWT. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session identity and landing payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid access JWT. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend handled the request for an authorized person. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in with no roles (pending access). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "pending_access",
                     *       "message": "A recognized role is required."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description People and unused invites with roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleResponse"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles and their attached permissions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolesResponse"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Created role with attached permissions (none yet). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Another role already uses this name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "duplicate_role_name",
                     *       "message": "A role with that name already exists."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Person not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Would remove the last access-administration grant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "last_admin_required",
                     *       "message": "At least one person with access administration must remain."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description Person after the assignment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Person or role not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The person already has this role. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "duplicate_assignment",
                     *       "message": "That role is already assigned."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person after the revoke. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Person, role, or assignment not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Would remove the last access-administration grant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "last_admin_required",
                     *       "message": "At least one person with access administration must remain."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description Invite recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A listed roleId was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email already invited or already belongs to a listed person. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite cancelled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Active unused invite not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignInviteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description Invite person after the assignment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invite or role not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The invite already has this role. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "duplicate_assignment",
                     *       "message": "That role is already assigned."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revokeInviteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: components["parameters"]["InviteId"];
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite person after the revoke. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invite, role, or assignment not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role is still assigned, or last access-administration path. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Updated role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Another role already uses this name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "duplicate_role_name",
                     *       "message": "A role with that name already exists."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    attachPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachPermissionRequest"];
            };
        };
        responses: {
            /** @description Role after the attach. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role or permission not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The role already has this permission. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "duplicate_permission",
                     *       "message": "That permission is already attached."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    detachPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
                permissionId: components["parameters"]["PermissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role after the detach. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role, permission, or attachment not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Would remove the last access-administration grant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "last_admin_required",
                     *       "message": "At least one person with access administration must remain."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing permissions, including module and optional action. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionsResponse"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Combined permissions do not include access_administration. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
