/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Working-and-connected check
         * @description Returns whether this backend handled the request and whether PostgreSQL and S3-compatible storage are reachable. HTTP 200 means the frontend reached the backend (connected successfully), even if database or storage is unavailable. If this operation cannot be completed because the backend is unreachable, the client MUST treat the application as not connected and MUST NOT show a connected-success message.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponse: {
            /**
             * @description Backend process handled GET /v1/status.
             * @enum {string}
             */
            service: "ok";
            /**
             * @description Result of a PostgreSQL reachability check (SELECT 1).
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * @description Result of an S3-compatible reachability check (HeadBucket).
             * @enum {string}
             */
            storage: "ok" | "unavailable";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend handled the request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
}
